apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
  labels:
    name: springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - name: springappcontainer
        image: ankamkrishnakanth/spring-boot-mongo
        ports:
        - name: springboot
          containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    name: springboot
spec:
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
# Mongo rc(HostPath)
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
     metadata:
       labels:
         name: mongo
     spec:
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
           hostPort: 27017
         volumeMounts:
         - name: mongodb-ps
           mountPath: /data/db
        volumes:
        - name: mongodb-ps
          hostPath:
            path: /tmp/dbbackup
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
